### ISSUE TITLE
插件Bug？？？

### ISSUE THREAD

**Issue by lilyfanfan** [3DTech-Steven7/MayaToRizomuv#1]
成功安装后。Maya的打开窗口在“Windows > Settings/Preferences > preferences > Files/Projects”中设置为“OS native”的时候（即跟随操作系统的样式，默认为：Maya default）,插件虽然可以打开RizomUV，但是传送功能会失效。

**Comment by 3DTech-Steven7** [comment]
收到你的反馈了，你可以暂时用Maya default来进行传递，后续会修复的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "3DTech-Steven7/MayaToRizomuv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 中午1:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[3DTech-Steven7/MayaToRizomuv] 插件Bug？？？ (#1)





 
成功安装后。Maya的打开窗口在“Windows &gt; Settings/Preferences &gt; preferences &gt; Files/Projects”中设置为“OS native”的时候（即跟随操作系统的样式，默认为：Maya default）,插件虽然可以打开RizomUV，但是传送功能会失效。

**Comment by lilyfanfan** [comment]
> 收到你的反馈了，你可以暂时用Maya default来进行传递，后续会修复的，谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "3DTech-Steven7/MayaToRizomuv" ***@***.***&gt;; 发送时间:&nbsp;2021年5月25日(星期二) 中午1:08 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[3DTech-Steven7/MayaToRizomuv] 插件Bug？？？ (#1) 成功安装后。Maya的打开窗口在“Windows &gt; Settings/Preferences &gt; preferences &gt; Files/Projects”中设置为“OS native”的时候（即跟随操作系统的样式，默认为：Maya default）,插件虽然可以打开RizomUV，但是传送功能会失效。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

辛苦了，多谢分享

**Comment by 3DTech-Steven7** [comment]
2022.4.25.04版本已修复

**Comment by 3DTech-Steven7** [comment]
> 2022.4.25.04版本已修复
